uploads = []
generated = []

[[outputs]]
id = "B1iruaromm9a3eOIio4fI"
uri = "file://docs/jira-backlog.md"
type = "text"
title = "EPIC: agile-artifact-analyzer — Jira Backlog"

[[outputs]]
id = "KTQXDNt_GvUrrR0COlyvv"
uri = "file://docs/system-design.md"
type = "text"
title = "Agile Artifact Analyzer — System Design"
